I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script
    S "Scientists have two ways of approaching reality."
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
OSError: Couldn't find file 'audio/Sensei_VO/sensei_1.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script
    S "Scientists have two ways of approaching reality."
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 583, in execute
    statement_name(stmt_name)
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 52, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 3022, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1205, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1183, in periodic_thread_main
    periodic_pass()
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\audio\audio.py", line 1125, in periodic_pass
    c.periodic()
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\ACER\Documents\RenPy\renpy-8.2.1-sdk\renpy\loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/Sensei_VO/sensei_1.mp3'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
A Lesson in Exodus 1.0
Fri Apr 26 21:47:33 2024
